"""Add Match model

Revision ID: 88999268147f
Revises: f1572ddbe0e7
Create Date: 2026-01-18 14:49:57.332983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88999268147f'
down_revision: Union[str, None] = 'f1572ddbe0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('my_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('last_message', sa.String(), nullable=True),
    sa.Column('last_message_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_by', sa.UUID(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['my_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sent_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('match_id'),
    sa.UniqueConstraint('my_id', 'partner_id', 'thread_id', name='uq_match_my_partner_thread')
    )
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=False)
    op.create_index(op.f('ix_matches_my_id'), 'matches', ['my_id'], unique=False)
    op.create_index(op.f('ix_matches_partner_id'), 'matches', ['partner_id'], unique=False)
    op.create_index(op.f('ix_matches_sent_by'), 'matches', ['sent_by'], unique=False)
    op.create_index(op.f('ix_matches_thread_id'), 'matches', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_thread_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_sent_by'), table_name='matches')
    op.drop_index(op.f('ix_matches_partner_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_my_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
