"""Add payment and payment_plan models

Revision ID: ac62038c0f20
Revises: 38c34cb1a342
Create Date: 2026-01-19 12:13:32.174775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac62038c0f20'
down_revision: Union[str, None] = '38c34cb1a342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_plans',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('MONTHLY', 'SEMI_ANNUAL', 'ANNUAL', 'VIP', 'TEST', name='planenum'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_payment_plans_plan_id'), 'payment_plans', ['plan_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_ref', sa.String(), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('mpesa_transaction_id', sa.String(), nullable=True),
    sa.Column('transaction_request', sa.JSON(), nullable=True),
    sa.Column('transaction_response', sa.JSON(), nullable=True),
    sa.Column('transaction_callback', sa.JSON(), nullable=True),
    sa.Column('transaction_status', sa.String(), nullable=True),
    sa.Column('date_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['payment_plans.plan_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payments_plan_id'), 'payments', ['plan_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_plan_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_payment_plans_plan_id'), table_name='payment_plans')
    op.drop_table('payment_plans')
    # ### end Alembic commands ###
