"""add_current_coordinates_and_preferences_to_profile

Revision ID: c17f6d6b5b96
Revises: ac62038c0f20
Create Date: 2026-01-20 18:50:22.909623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c17f6d6b5b96'
down_revision: Union[str, None] = 'ac62038c0f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('current_coordinates', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'preferences')
    op.drop_column('profiles', 'current_coordinates')
    # ### end Alembic commands ###
