"""Restructure User model and add Profile model

Revision ID: f1572ddbe0e7
Revises: 0d1c3b14c44f
Create Date: 2026-01-18 12:44:28.751545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1572ddbe0e7'
down_revision: Union[str, None] = '0d1c3b14c44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add new columns to users table (user_id nullable initially, will be populated from id)
    op.add_column('users', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('fcm_token', sa.String(), nullable=True))
    
    # Copy id to user_id for existing records (if any)
    op.execute("UPDATE users SET user_id = id WHERE user_id IS NULL")
    
    # Set defaults for first_name and last_name if they're None (for existing records)
    op.execute("UPDATE users SET first_name = '' WHERE first_name IS NULL")
    op.execute("UPDATE users SET last_name = '' WHERE last_name IS NULL")
    
    # Drop old id column and its index first (before making user_id primary key)
    op.drop_index('ix_users_id', table_name='users')
    op.drop_constraint('users_pkey', 'users', type_='primary')
    op.drop_column('users', 'id')
    
    # Now make user_id and other required fields non-nullable
    op.alter_column('users', 'user_id', nullable=False)
    op.alter_column('users', 'first_name', nullable=False)
    op.alter_column('users', 'last_name', nullable=False)
    
    # Create primary key constraint on user_id
    op.create_primary_key('users_pkey', 'users', ['user_id'])
    
    # Create indexes
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    
    # Create profiles table (now that user_id is a proper primary key)
    op.create_table('profiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('phone_number', name='uq_profile_phone_number'),
    sa.UniqueConstraint('user_id', name='uq_profile_user_id')
    )
    op.create_index(op.f('ix_profiles_phone_number'), 'profiles', ['phone_number'], unique=True)
    op.create_index(op.f('ix_profiles_profile_id'), 'profiles', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'fcm_token')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'user_id')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_profile_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_phone_number'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
